version: '3'
services:
  webserver:
    image: 'nginx:alpine'
    container_name: webserver
    restart: unless-stopped
    ports:
      - '8080:80'
      - '8443:443'
    volumes:
      - './web:/var/www/html'
      - './nginx/conf.d/:/etc/nginx/conf.d/'
    networks:
      file_auth_net:
        ipv4_address: 172.28.1.1

networks:
  file_auth_net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.28.0.0/16
      